pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

Item {
    id: config

    readonly property string homeDir: Quickshell.env("HOME")
    readonly property string userConfigDir: homeDir + "/.config/serpantinum"
    
    readonly property string settingsJsonPath: Quickshell.env("QS_SETTINGS") ? Quickshell.env("QS_SETTINGS") : (userConfigDir + "/settings.json")

    property bool dataReady: false
    property var rawSettings: ({})

    signal settingsLoaded()

    // Compatibility surface consumed only by the recovered pre-V2 SettingsPopup.
    property real uiScale: 1.0
    property bool openGuideAtStartup: true
    property bool topbarHelpIcon: true
    property int workspaceCount: 8
    property int initialWorkspaceCount: 8
    property string wallpaperDir: Quickshell.env("WALLPAPER_DIR") || (homeDir + "/Pictures/Wallpapers")
    property string language: ""
    property string kbOptions: "grp:alt_shift_toggle"
    property string weatherUnit: "metric"
    property string weatherApiKey: ""
    property string weatherCityId: ""
    property var keybindsData: []
    signal keybindsLoaded()
    property var startupData: []
    signal startupLoaded()
    property alias monitorsModel: legacyMonitorsModel
    ListModel { id: legacyMonitorsModel }
    property int monActiveEditIndex: 0
    property real monUiScale: 0.10
    property int monOriginalOriginX: 0
    property int monOriginalOriginY: 0
    property alias displayPoller: legacyDisplayPoller
    property alias monDelayedLayoutUpdate: legacyLayoutTimer

    function legacyShellQuote(value) {
        return "'" + String(value).replace(/'/g, "'\\''") + "'";
    }

    function monIsOverlapping(ax, ay, aw, ah, bx, by, bw, bh) {
        return ax < bx + bw && ax + aw > bx && ay < by + bh && ay + ah > by;
    }

    function monIsOverlappingAny(x, y, w, h, skipIdx) {
        for (let i = 0; i < monitorsModel.count; i++) {
            if (i === skipIdx) continue;
            let m = monitorsModel.get(i);
            let portrait = m.transform === 1 || m.transform === 3;
            let mw = (portrait ? m.resH : m.resW) / m.sysScale * monUiScale;
            let mh = (portrait ? m.resW : m.resH) / m.sysScale * monUiScale;
            if (monIsOverlapping(x, y, w, h, m.uiX, m.uiY, mw, mh)) return true;
        }
        return false;
    }

    function monGetPerimeterSnap(px, py, sx, sy, sw, sh, mw, mh, snap) {
        let candidates = [
            { x: sx - mw, y: py }, { x: sx + sw, y: py },
            { x: px, y: sy - mh }, { x: px, y: sy + sh }
        ];
        let best = candidates[0];
        let distance = Number.MAX_VALUE;
        for (let candidate of candidates) {
            let d = Math.hypot(px - candidate.x, py - candidate.y);
            if (d < distance) { best = candidate; distance = d; }
        }
        return { x: Math.abs(px - best.x) <= snap ? best.x : px, y: Math.abs(py - best.y) <= snap ? best.y : py };
    }

    function monForceLayoutUpdate() {}

    function saveAppSettings() {
        updateJsonBulk({
            uiScale: config.uiScale,
            openGuideAtStartup: config.openGuideAtStartup,
            topbarHelpIcon: config.topbarHelpIcon,
            wallpaperDir: config.wallpaperDir,
            language: config.language,
            kbOptions: config.kbOptions,
            workspaceCount: config.workspaceCount
        });
    }

    function saveWeatherConfig() {
        updateJsonBulk({
            weatherUnit: config.weatherUnit,
            weatherApiKey: config.weatherApiKey,
            weatherCityId: config.weatherCityId
        });
    }

    function saveAllKeybinds(bindsArray) {
        config.keybindsData = bindsArray;
        setSetting("keybinds", bindsArray);
        Quickshell.execDetached(["python3", homeDir + "/.local/share/quickshell-addons/serpantinum-settings/keybinds_v2.py", "save", JSON.stringify(bindsArray)]);
        Quickshell.execDetached(["hyprctl", "reload"]);
    }

    function saveAllStartup(startupArray) {
        config.startupData = startupArray;
        setSetting("startup", startupArray);
    }

    function applyMonitors() {
        let lines = ["-- Generated by legacy SettingsPopup --"];
        for (let i = 0; i < monitorsModel.count; i++) {
            let m = monitorsModel.get(i);
            let x = Math.round((m.uiX || 0) / monUiScale);
            let y = Math.round((m.uiY || 0) / monUiScale);
            let line = "hl.monitor({ output = " + JSON.stringify(m.name) + ", mode = " + JSON.stringify(m.resW + "x" + m.resH + "@" + m.rate) + ", position = " + JSON.stringify(x + "x" + y) + ", scale = " + Number(m.sysScale || 1);
            if (Number(m.transform || 0) !== 0) line += ", transform = " + Number(m.transform);
            lines.push(line + " })");
        }
        sh("printf '%s\\n' " + legacyShellQuote(lines.join("\n")) + " > " + legacyShellQuote(homeDir + "/.config/hypr/config/monitors.lua") + "; hyprctl reload");
    }

    Process {
        id: legacyDisplayPoller
        command: ["hyprctl", "monitors", "-j"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    let data = JSON.parse(text.trim());
                    legacyMonitorsModel.clear();
                    let minX = 999999, minY = 999999;
                    for (let monitor of data) { minX = Math.min(minX, monitor.x); minY = Math.min(minY, monitor.y); }
                    config.monOriginalOriginX = minX === 999999 ? 0 : minX;
                    config.monOriginalOriginY = minY === 999999 ? 0 : minY;
                    for (let i = 0; i < data.length; i++) {
                        let monitor = data[i];
                        legacyMonitorsModel.append({ name: monitor.name, resW: monitor.width, resH: monitor.height, sysScale: monitor.scale || 1, rate: Math.round(monitor.refreshRate || 60).toString(), uiX: (monitor.x - config.monOriginalOriginX) * monUiScale, uiY: (monitor.y - config.monOriginalOriginY) * monUiScale, transform: monitor.transform || 0, availableModes: JSON.stringify(monitor.availableModes || []) });
                        if (monitor.focused) config.monActiveEditIndex = i;
                    }
                } catch (error) {}
            }
        }
    }

    Timer { id: legacyLayoutTimer; interval: 10; repeat: false; onTriggered: config.monForceLayoutUpdate() }

    Process {
        id: legacyKeybindReader
        command: ["python3", homeDir + "/.local/share/quickshell-addons/serpantinum-settings/keybinds_v2.py", "list"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    let data = JSON.parse(text.trim());
                    config.keybindsData = Array.isArray(data) ? data : [];
                } catch (error) {
                    config.keybindsData = [];
                }
                config.keybindsLoaded();
            }
        }
    }

    function sh(cmd) {
        Quickshell.execDetached(["bash", "-c", cmd]);
    }

    function getSetting(key, fallbackValue) {
        return (rawSettings && rawSettings.hasOwnProperty(key)) ? rawSettings[key] : fallbackValue;
    }

    function setSetting(key, value) {
        let temp = Object.assign({}, rawSettings);
        temp[key] = value;
        rawSettings = temp;

        let safeValue = typeof value === "string" ? `"${value}"` : value;
        if (typeof value === "object") safeValue = JSON.stringify(value).replace(/'/g, "'\\''");

        let cmd = `mkdir -p "$(dirname '${settingsJsonPath}')" && ` +
                  `[ ! -s '${settingsJsonPath}' ] && echo '{}' > '${settingsJsonPath}'; ` +
                  `jq '. + {"${key}": ${safeValue}}' '${settingsJsonPath}' > '${settingsJsonPath}.tmp' 2>/dev/null && ` +
                  `jq -e . '${settingsJsonPath}.tmp' > /dev/null 2>&1 && ` +
                  `cp '${settingsJsonPath}.tmp' '${settingsJsonPath}' && rm -f '${settingsJsonPath}.tmp'`;
        sh(cmd);
    }

    function updateJsonBulk(dataObj) {
        let jsonStr = JSON.stringify(dataObj).replace(/'/g, "'\\''");
        let cmd = `mkdir -p "$(dirname '${settingsJsonPath}')" && ` +
                  `[ ! -s '${settingsJsonPath}' ] && echo '{}' > '${settingsJsonPath}'; ` +
                  `jq '. + ${jsonStr}' '${settingsJsonPath}' > '${settingsJsonPath}.tmp' 2>/dev/null && ` +
                  `jq -e . '${settingsJsonPath}.tmp' > /dev/null 2>&1 && ` +
                  `cp '${settingsJsonPath}.tmp' '${settingsJsonPath}' && rm -f '${settingsJsonPath}.tmp'`;
        sh(cmd);
        
        let temp = Object.assign({}, rawSettings);
        for (let key in dataObj) {
            temp[key] = dataObj[key];
        }
        rawSettings = temp;
    }

    FileView {
        id: settingsWatcher
        path: config.settingsJsonPath
        watchChanges: true
        onFileChanged: reload()
        
        onLoaded: {
            try {
                let raw = typeof text === "function" ? text() : text;
                if (typeof raw === "string") {
                    let trimmed = raw.trim();
                    if (trimmed.length > 0) {
                        config.rawSettings = JSON.parse(trimmed);
                    }
                }
            } catch (e) {
            }
            config.settingsLoaded();
            config.dataReady = true;
            let settings = config.rawSettings || {};
            if (settings.uiScale !== undefined) config.uiScale = settings.uiScale;
            if (settings.openGuideAtStartup !== undefined) config.openGuideAtStartup = settings.openGuideAtStartup;
            if (settings.topbarHelpIcon !== undefined) config.topbarHelpIcon = settings.topbarHelpIcon;
            if (settings.workspaceCount !== undefined) {
                config.workspaceCount = settings.workspaceCount;
                config.initialWorkspaceCount = settings.workspaceCount;
            }
            if (settings.wallpaperDir !== undefined) config.wallpaperDir = settings.wallpaperDir;
            if (settings.language !== undefined) config.language = settings.language;
            if (settings.kbOptions !== undefined) config.kbOptions = settings.kbOptions;
            if (settings.weatherUnit !== undefined) config.weatherUnit = settings.weatherUnit;
            if (settings.weatherApiKey !== undefined) config.weatherApiKey = settings.weatherApiKey;
            if (settings.weatherCityId !== undefined) config.weatherCityId = settings.weatherCityId;
            if (Array.isArray(settings.keybinds)) {
                config.keybindsData = settings.keybinds;
                config.keybindsLoaded();
            } else {
                legacyKeybindReader.running = true;
            }
            config.startupData = Array.isArray(settings.startup) ? settings.startup : [];
            config.startupLoaded();
        }
    }

    Component.onCompleted: {
        if (settingsWatcher.path) {
            settingsWatcher.reload();
        }
    }
}
