#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADDONS_SRC="$REPO_DIR/addons"
SYSTEMD_SRC="$REPO_DIR/systemd/user"

ADDONS_DST="${XDG_DATA_HOME:-$HOME/.local/share}/quickshell-addons"
SYSTEMD_DST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
HYPR_BASE="${HYPR_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr}"

warn() {
    echo "warning: $*" >&2
}

is_stub_hypr_config() {
    [[ -f "$HYPR_BASE/hyprland.conf" ]] && grep -q 'autogenerated = 1' "$HYPR_BASE/hyprland.conf"
}

resolve_quickshell_dir() {
    if [[ -n "${HYPR_QUICKSHELL_DIR:-}" ]]; then
        echo "$HYPR_QUICKSHELL_DIR"
        return 0
    fi

    if [[ -f "$HYPR_BASE/scripts/quickshell/WindowRegistry.js" ]]; then
        echo "$HYPR_BASE/scripts/quickshell"
        return 0
    fi

    if [[ -f "$HYPR_BASE/hypr/scripts/quickshell/WindowRegistry.js" ]]; then
        warn "using nested hypr config at $HYPR_BASE/hypr; run the ilyamiro installer to fix the layout"
        echo "$HYPR_BASE/hypr/scripts/quickshell"
        return 0
    fi

    echo "$HYPR_BASE/scripts/quickshell"
}

QUICKSHELL_DIR="$(resolve_quickshell_dir)"
WALLPAPER_PICKER="$QUICKSHELL_DIR/wallpaper/WallpaperPicker.qml"
WINDOW_REGISTRY="$QUICKSHELL_DIR/WindowRegistry.js"
HYPR_SETTINGS="${HYPR_SETTINGS:-$HYPR_BASE/settings.json}"

install_addon() {
    local name="$1"
    local src="$ADDONS_SRC/$name"
    local dst="$ADDONS_DST/$name"

    if [[ ! -d "$src" ]]; then
        echo "error: addon source not found: $src" >&2
        exit 1
    fi

    mkdir -p "$dst"
    cp -a "$src/." "$dst/"
    chmod +x "$dst/apply.sh" "$dst/apply.py"
}

install_systemd_units() {
    mkdir -p "$SYSTEMD_DST"

    local unit
    for unit in "$SYSTEMD_SRC"/*; do
        [[ -f "$unit" ]] || continue
        sed \
            -e "s#%h/.local/share/quickshell-addons#${ADDONS_DST}#g" \
            -e "s#%h/.config/hypr#${HYPR_BASE}#g" \
            "$unit" > "$SYSTEMD_DST/$(basename "$unit")"
    done
}

user_systemctl() {
    if [[ -z "${XDG_RUNTIME_DIR:-}" ]]; then
        return 1
    fi
    systemctl --user "$@"
}

run_apply() {
  env \
    XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}" \
    XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}" \
    HYPR_CONFIG_DIR="$HYPR_BASE" \
    HYPR_QUICKSHELL_DIR="$QUICKSHELL_DIR" \
    HYPR_SETTINGS="$HYPR_SETTINGS" \
    WALLPAPER_RANDOM_PICKER="$WALLPAPER_PICKER" \
    "$@"
}

install_addon "wallpaper-random"
install_addon "emoji-picker"
install_systemd_units

if user_systemctl daemon-reload; then
    if ! user_systemctl enable --now wallpaper-random-addon.path emoji-picker-addon.path; then
        warn "could not enable addon watcher units"
        echo "  run: systemctl --user enable --now wallpaper-random-addon.path emoji-picker-addon.path" >&2
    fi
else
    warn "user systemd session is not available; units were installed but not enabled"
    echo "  after logging into a graphical session, run:" >&2
    echo "    systemctl --user daemon-reload" >&2
    echo "    systemctl --user enable --now wallpaper-random-addon.path emoji-picker-addon.path" >&2
fi

patch_failures=0

if is_stub_hypr_config; then
    warn "hyprland is using an auto-generated stub config at $HYPR_BASE/hyprland.conf"
    echo "  install ilyamiro imperative-dots first:" >&2
    echo '    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ilyamiro/imperative-dots/master/install.sh)"' >&2
    echo "  then re-run ./install.sh to apply these addons" >&2
    patch_failures=2
else
    if [[ -f "$WALLPAPER_PICKER" ]]; then
        if ! run_apply WALLPAPER_RANDOM_APPLY_DELAY=0 "$ADDONS_DST/wallpaper-random/apply.sh"; then
            warn "wallpaper-random patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "upstream wallpaper picker not found at $WALLPAPER_PICKER"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$WINDOW_REGISTRY" && -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply EMOJI_PICKER_APPLY_DELAY=0 "$ADDONS_DST/emoji-picker/apply.sh"; then
            warn "emoji-picker patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "upstream Quickshell config not found (expected $WINDOW_REGISTRY and $HYPR_SETTINGS)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi
fi

compile_hypr_keybinds() {
    local watcher="$HYPR_BASE/scripts/settings_watcher.sh"
    if [[ -f "$watcher" ]]; then
        bash "$watcher" --compile
    else
        hyprctl reload >/dev/null 2>&1 || true
    fi
}

if ! is_stub_hypr_config; then
    compile_hypr_keybinds
fi

if (( patch_failures > 0 )); then
    echo "Installed addon files and systemd units. $patch_failures patch step(s) will retry once upstream dots are available."
    exit 0
fi

echo "Installed wallpaper-random and emoji-picker addons."
