#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ADDONS_SRC="$REPO_DIR/addons"
SYSTEMD_SRC="$REPO_DIR/systemd/user"

ADDONS_DST="${XDG_DATA_HOME:-$HOME/.local/share}/quickshell-addons"
SYSTEMD_DST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
HYPR_BASE="${HYPR_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr}"
MATUGEN_BASE="${MATUGEN_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/matugen}"
CACHE_BASE="${XDG_CACHE_HOME:-$HOME/.cache}"

warn() {
    echo "warning: $*" >&2
}

is_stub_hypr_config() {
    [[ -f "$HYPR_BASE/hyprland.conf" ]] && grep -q 'autogenerated = 1' "$HYPR_BASE/hyprland.conf"
}

resolve_quickshell_dir() {
    if [[ -n "${HYPR_QUICKSHELL_DIR:-}" ]]; then
        echo "$HYPR_QUICKSHELL_DIR"
        return 0
    fi

    if [[ -f "$HYPR_BASE/scripts/quickshell/WindowRegistry.js" ]]; then
        echo "$HYPR_BASE/scripts/quickshell"
        return 0
    fi

    if [[ -f "$HYPR_BASE/hypr/scripts/quickshell/WindowRegistry.js" ]]; then
        warn "using nested hypr config at $HYPR_BASE/hypr; run the ilyamiro installer to fix the layout"
        echo "$HYPR_BASE/hypr/scripts/quickshell"
        return 0
    fi

    echo "$HYPR_BASE/scripts/quickshell"
}

QUICKSHELL_DIR="$(resolve_quickshell_dir)"
WALLPAPER_PICKER="$QUICKSHELL_DIR/wallpaper/WallpaperPicker.qml"
QS_MANAGER="$HYPR_BASE/scripts/qs_manager.sh"
WINDOW_REGISTRY="$QUICKSHELL_DIR/WindowRegistry.js"
HYPR_SETTINGS="${HYPR_SETTINGS:-$HYPR_BASE/settings.json}"
MATUGEN_SETTINGS_POPUP="$QUICKSHELL_DIR/settings/SettingsPopup.qml"
MATUGEN_CONFIG="${MATUGEN_CONFIG:-$MATUGEN_BASE/config.toml}"
MATUGEN_QS_TEMPLATE="${MATUGEN_QS_TEMPLATE:-$MATUGEN_BASE/templates/qs_colors.json.template}"
MATUGEN_RELOAD_SCRIPT="$QUICKSHELL_DIR/wallpaper/matugen_reload.sh"
MATUGEN_WALLPAPER_CACHE="${MATUGEN_WALLPAPER_CACHE:-$CACHE_BASE/quickshell/wallpaper_picker/current_wallpaper.png}"
SCREENSHOT_SCRIPT="$HYPR_BASE/scripts/screenshot.sh"
SCREENSHOT_OVERLAY="$QUICKSHELL_DIR/ScreenshotOverlay.qml"
SCREENSHOT_SETTINGS_POPUP="$QUICKSHELL_DIR/settings/SettingsPopup.qml"
TOPBAR_QML="$QUICKSHELL_DIR/TopBar.qml"
MAIN_QML="$QUICKSHELL_DIR/Main.qml"
ADDON_SETTINGS_PAGE="$QUICKSHELL_DIR/settings/AddonSettingsPage.qml"
APP_LAUNCHER_QML="$QUICKSHELL_DIR/applauncher/appLauncher.qml"
TIMER_QML="$QUICKSHELL_DIR/quickactions/Timer.qml"
VOLUME_POPUP_QML="$QUICKSHELL_DIR/volume/VolumePopup.qml"
NETWORK_POPUP_QML="$QUICKSHELL_DIR/network/NetworkPopup.qml"

install_addon() {
    local name="$1"
    local src="$ADDONS_SRC/$name"
    local dst="$ADDONS_DST/$name"

    if [[ ! -d "$src" ]]; then
        echo "error: addon source not found: $src" >&2
        exit 1
    fi

    mkdir -p "$dst"
    cp -a "$src/." "$dst/"
    chmod +x "$dst/apply.sh" "$dst/apply.py"
    if [[ -f "$dst/zoomit.py" ]]; then
        chmod +x "$dst/zoomit.py"
    fi
    if [[ -f "$dst/loopback.py" ]]; then
        chmod +x "$dst/loopback.py"
    fi
}

install_systemd_units() {
    mkdir -p "$SYSTEMD_DST"

    local unit
    for unit in "$SYSTEMD_SRC"/*; do
        [[ -f "$unit" ]] || continue
        sed \
            -e "s#%h/.local/share/quickshell-addons#${ADDONS_DST}#g" \
            -e "s#%h/.config/hypr#${HYPR_BASE}#g" \
            -e "s#%h/.config/matugen#${MATUGEN_BASE}#g" \
            "$unit" > "$SYSTEMD_DST/$(basename "$unit")"
    done
}

user_systemctl() {
    if [[ -z "${XDG_RUNTIME_DIR:-}" ]]; then
        return 1
    fi
    systemctl --user "$@"
}

run_apply() {
  env \
    XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}" \
    XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}" \
    HYPR_CONFIG_DIR="$HYPR_BASE" \
    HYPR_QUICKSHELL_DIR="$QUICKSHELL_DIR" \
    HYPR_SETTINGS="$HYPR_SETTINGS" \
    MATUGEN_CONFIG_DIR="$MATUGEN_BASE" \
    MATUGEN_CONFIG="$MATUGEN_CONFIG" \
    MATUGEN_QS_TEMPLATE="$MATUGEN_QS_TEMPLATE" \
    MATUGEN_SETTINGS_POPUP="$MATUGEN_SETTINGS_POPUP" \
    MATUGEN_RELOAD_SCRIPT="$MATUGEN_RELOAD_SCRIPT" \
    MATUGEN_WALLPAPER_CACHE="$MATUGEN_WALLPAPER_CACHE" \
    SCREENSHOT_FREEZE_SCRIPT="$SCREENSHOT_SCRIPT" \
    SCREENSHOT_FREEZE_OVERLAY="$SCREENSHOT_OVERLAY" \
    SCREENSHOT_FREEZE_SETTINGS_POPUP="$SCREENSHOT_SETTINGS_POPUP" \
    MUSIC_PREVIEW_TOPBAR="$TOPBAR_QML" \
    MUSIC_VISUALIZER_SETTINGS_POPUP="$SCREENSHOT_SETTINGS_POPUP" \
    TOPBAR_EFFECTS_MAIN="$MAIN_QML" \
    TOPBAR_EFFECTS_TOPBAR="$TOPBAR_QML" \
    TOPBAR_EFFECTS_SETTINGS_POPUP="$SCREENSHOT_SETTINGS_POPUP" \
    TOPBAR_EFFECTS_ADDON_SETTINGS="$ADDON_SETTINGS_PAGE" \
    HEADSET_MIC_VOLUME_POPUP="$VOLUME_POPUP_QML" \
    CUSTOM_ALARM_TIMER_QML="$TIMER_QML" \
    WALLPAPER_RANDOM_PICKER="$WALLPAPER_PICKER" \
    WALLPAPER_RANDOM_MANAGER="$QS_MANAGER" \
    "$@"
}

repair_wallpaper_backend() {
    if ! command -v awww >/dev/null 2>&1 || command -v swww >/dev/null 2>&1; then
        return 0
    fi

    local file
    for file in \
        "$HYPR_BASE/scripts/qs_manager.sh" \
        "$QUICKSHELL_DIR/Config.qml" \
        "$QUICKSHELL_DIR/wallpaper/WallpaperPicker.qml"; do
        [[ -f "$file" ]] || continue
        sed -i \
            -e 's/swww-daemon/awww-daemon/g' \
            -e 's/\<swww\>/awww/g' \
            "$file"
    done
}

install_addon "wallpaper-random"
install_addon "emoji-picker"
install_addon "matugen-vibrant"
install_addon "zoomit"
install_addon "screenshot-freeze"
install_addon "idle-inhibit"
install_addon "music-preview-rounded"
install_addon "topbar-button-effects"
install_addon "launcher-web-search"
install_addon "custom-alarm-clock"
install_addon "headset-mic-loopback"
install_addon "captive-portal"
install_addon "speedtest"
install_addon "loading-icon"
install_addon "wifi-text-scroll"
install_systemd_units

if user_systemctl daemon-reload; then
    if ! user_systemctl try-restart hypr-zoomit.service; then
        warn "could not refresh the ZoomIt zoom daemon"
    fi
    if ! user_systemctl enable --now wallpaper-random-addon.path emoji-picker-addon.path matugen-vibrant-addon.path zoomit-addon.path screenshot-freeze-addon.path idle-inhibit-addon.path music-preview-rounded-addon.path topbar-button-effects-addon.path launcher-web-search-addon.path custom-alarm-clock-addon.path headset-mic-loopback-addon.path captive-portal-addon.path speedtest-addon.path loading-icon-addon.path wifi-text-scroll-addon.path; then
        warn "could not enable addon watcher units"
        echo "  run: systemctl --user enable --now wallpaper-random-addon.path emoji-picker-addon.path matugen-vibrant-addon.path zoomit-addon.path screenshot-freeze-addon.path idle-inhibit-addon.path music-preview-rounded-addon.path topbar-button-effects-addon.path launcher-web-search-addon.path custom-alarm-clock-addon.path headset-mic-loopback-addon.path captive-portal-addon.path speedtest-addon.path loading-icon-addon.path wifi-text-scroll-addon.path" >&2
    fi
else
    warn "user systemd session is not available; units were installed but not enabled"
    echo "  after logging into a graphical session, run:" >&2
    echo "    systemctl --user daemon-reload" >&2
    echo "    systemctl --user enable --now wallpaper-random-addon.path emoji-picker-addon.path matugen-vibrant-addon.path zoomit-addon.path screenshot-freeze-addon.path idle-inhibit-addon.path music-preview-rounded-addon.path topbar-button-effects-addon.path launcher-web-search-addon.path custom-alarm-clock-addon.path headset-mic-loopback-addon.path captive-portal-addon.path speedtest-addon.path loading-icon-addon.path wifi-text-scroll-addon.path" >&2
fi

patch_failures=0

if is_stub_hypr_config; then
    warn "hyprland is using an auto-generated stub config at $HYPR_BASE/hyprland.conf"
    echo "  install ilyamiro imperative-dots first:" >&2
    echo '    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ilyamiro/imperative-dots/master/install.sh)"' >&2
    echo "  then re-run ./install.sh to apply these addons" >&2
    patch_failures=2
else
    if [[ -f "$WALLPAPER_PICKER" && -f "$QS_MANAGER" ]]; then
        if ! run_apply WALLPAPER_RANDOM_APPLY_DELAY=0 "$ADDONS_DST/wallpaper-random/apply.sh"; then
            warn "wallpaper-random patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "upstream wallpaper files not found (expected $WALLPAPER_PICKER and $QS_MANAGER)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$WINDOW_REGISTRY" && -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply EMOJI_PICKER_APPLY_DELAY=0 "$ADDONS_DST/emoji-picker/apply.sh"; then
            warn "emoji-picker patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "upstream Quickshell config not found (expected $WINDOW_REGISTRY and $HYPR_SETTINGS)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$MATUGEN_SETTINGS_POPUP" && -f "$MATUGEN_CONFIG" && -f "$MATUGEN_QS_TEMPLATE" ]]; then
        if ! run_apply MATUGEN_VIBRANT_APPLY_DELAY=0 "$ADDONS_DST/matugen-vibrant/apply.sh"; then
            warn "matugen-vibrant patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "upstream Matugen settings files not found (expected $MATUGEN_SETTINGS_POPUP, $MATUGEN_CONFIG and $MATUGEN_QS_TEMPLATE)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply ZOOMIT_APPLY_DELAY=0 "$ADDONS_DST/zoomit/apply.sh"; then
            warn "zoomit patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Hyprland settings not found (expected $HYPR_SETTINGS)"
        echo "  install the Hyprland dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$SCREENSHOT_SCRIPT" && -f "$SCREENSHOT_OVERLAY" && -f "$SCREENSHOT_SETTINGS_POPUP" && -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply SCREENSHOT_FREEZE_APPLY_DELAY=0 "$ADDONS_DST/screenshot-freeze/apply.sh"; then
            warn "screenshot-freeze patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "screenshot files not found (expected $SCREENSHOT_SCRIPT, $SCREENSHOT_OVERLAY, $SCREENSHOT_SETTINGS_POPUP and $HYPR_SETTINGS)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$TOPBAR_QML" && -f "$SCREENSHOT_SETTINGS_POPUP" && -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply MUSIC_PREVIEW_ROUNDED_APPLY_DELAY=0 "$ADDONS_DST/music-preview-rounded/apply.sh"; then
            warn "music-preview-rounded patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Quickshell music visualizer files not found (expected $TOPBAR_QML, $SCREENSHOT_SETTINGS_POPUP and $HYPR_SETTINGS)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$MAIN_QML" && -f "$TOPBAR_QML" && -f "$SCREENSHOT_SETTINGS_POPUP" && -f "$ADDON_SETTINGS_PAGE" && -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply TOPBAR_BUTTON_EFFECTS_APPLY_DELAY=0 "$ADDONS_DST/topbar-button-effects/apply.sh"; then
            warn "topbar-button-effects patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Quickshell top bar animation files not found (expected $MAIN_QML, $TOPBAR_QML, $SCREENSHOT_SETTINGS_POPUP, $ADDON_SETTINGS_PAGE and $HYPR_SETTINGS)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$HYPR_SETTINGS" ]]; then
        if ! run_apply IDLE_INHIBIT_APPLY_DELAY=0 "$ADDONS_DST/idle-inhibit/apply.sh"; then
            warn "idle-inhibit patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Hyprland settings not found (expected $HYPR_SETTINGS)"
        echo "  install the Hyprland dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$APP_LAUNCHER_QML" ]]; then
        if ! run_apply LAUNCHER_WEB_SEARCH_APPLY_DELAY=0 LAUNCHER_WEB_SEARCH_QML="$APP_LAUNCHER_QML" "$ADDONS_DST/launcher-web-search/apply.sh"; then
            warn "launcher-web-search patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Quickshell app launcher not found (expected $APP_LAUNCHER_QML)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$TIMER_QML" ]]; then
        if ! run_apply CUSTOM_ALARM_APPLY_DELAY=0 "$ADDONS_DST/custom-alarm-clock/apply.sh"; then
            warn "custom-alarm-clock patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Quickshell Timer widget not found (expected $TIMER_QML)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$VOLUME_POPUP_QML" ]]; then
        if ! run_apply HEADSET_MIC_LOOPBACK_APPLY_DELAY=0 "$ADDONS_DST/headset-mic-loopback/apply.sh"; then
            warn "headset-mic-loopback patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Quickshell audio panel not found (expected $VOLUME_POPUP_QML)"
        echo "  install the Hyprland/Quickshell dots first; the watcher will apply this addon later" >&2
        patch_failures=$((patch_failures + 1))
    fi

    if [[ -f "$NETWORK_POPUP_QML" ]]; then
        if ! run_apply "$ADDONS_DST/captive-portal/apply.sh"; then
            warn "captive-portal patch failed"
            patch_failures=$((patch_failures + 1))
        fi
        if ! run_apply "$ADDONS_DST/speedtest/apply.sh"; then
            warn "speedtest patch failed"
            patch_failures=$((patch_failures + 1))
        fi
        if ! run_apply LOADING_ICON_APPLY_DELAY=0 "$ADDONS_DST/loading-icon/apply.sh"; then
            warn "loading-icon patch failed"
            patch_failures=$((patch_failures + 1))
        fi
        if ! run_apply WIFI_TEXT_SCROLL_APPLY_DELAY=0 "$ADDONS_DST/wifi-text-scroll/apply.sh"; then
            warn "wifi-text-scroll patch failed"
            patch_failures=$((patch_failures + 1))
        fi
    else
        warn "Quickshell network panel not found (expected $NETWORK_POPUP_QML)"
        echo "  install the Hyprland/Quickshell dots first; the watchers will apply these addons later" >&2
        patch_failures=$((patch_failures + 4))
    fi
fi

compile_hypr_config() {
    local watcher="$HYPR_BASE/scripts/settings_watcher.sh"
    if [[ -f "$watcher" ]]; then
        bash "$watcher" --compile
    fi

    # The upstream compiler skips `hyprctl reload` when the generated files are
    # byte-for-byte identical. That is normally useful, but it leaves a running
    # Hyprland instance on its defaults after a fresh install/session repair.
    # Always reload here so borders, animations and keyboard layouts on disk
    # become the values that are actually active.
    if command -v hyprctl >/dev/null 2>&1; then
        if hyprctl reload >/dev/null 2>&1; then
            echo "Hyprland configuration reloaded."
        else
            warn "Hyprland is not reachable; its configuration will load at the next session."
        fi
    fi
}

reload_quickshell_settings() {
    local shell_qml="$QUICKSHELL_DIR/Shell.qml"
    if command -v qs >/dev/null 2>&1 && [[ -f "$shell_qml" ]]; then
        qs -p "$shell_qml" ipc call main forceReload >/dev/null 2>&1 || true
    fi
}

if ! is_stub_hypr_config; then
    repair_wallpaper_backend
    compile_hypr_config
    reload_quickshell_settings
fi

if (( patch_failures > 0 )); then
    echo "error: installed addon files and systemd units, but $patch_failures patch step(s) failed." >&2
    echo "Review the detailed warning(s) above; watcher units will retry after the missing or invalid upstream files are fixed." >&2
    exit 1
fi

echo "Installed wallpaper-random, emoji-picker, matugen-vibrant, zoomit, screenshot-freeze, idle-inhibit, music-preview-rounded, topbar-button-effects, launcher-web-search, custom-alarm-clock, headset-mic-loopback, captive-portal, speedtest, loading-icon and wifi-text-scroll addons."
